version: '3'
services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports: 
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__database=ghost
      - database__connection__host=database
      - database__connection__user=root
      - database__connection__password=senha
    depends_on:
      - database
    networks:
      - my-network
      
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=senha
    volumes:
      - dados-do-banco:/var/lib/mysql
    networks:
      - my-network

volumes:
 dados-do-banco:
networks:
  my-network: